# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 Francesco Campanile
"""add cascade delete for test set entries

Revision ID: 03a774b2b416
Revises: 47cfdc148f48
Create Date: 2026-07-08 17:16:19.658742

"""
from collections.abc import Sequence

from alembic import op

revision: str = '03a774b2b416'
down_revision: str | None = '47cfdc148f48'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_set_entries', schema=None) as batch_op:
        batch_op.create_foreign_key("cascade_delete_for_test_set_entries",
                                    'test_sets', ['test_set_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_set_entries', schema=None) as batch_op:
        batch_op.drop_constraint("cascade_delete_for_test_set_entries", type_='foreignkey')
        batch_op.create_foreign_key(None, 'test_sets', ['test_set_id'], ['id'])

    # ### end Alembic commands ###
