# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 Francesco Campanile
"""updated snapshotted data

Revision ID: 47cfdc148f48
Revises: 78f9e1ada61a
Create Date: 2026-07-03 15:43:09.032480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '47cfdc148f48'
down_revision: Union[str, None] = '78f9e1ada61a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_set_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('model_output', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_set_entries', schema=None) as batch_op:
        batch_op.drop_column('model_output')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
