"""adding on delete cascade for deleted tests against test type assignments

Revision ID: 54bad840a98c
Revises: dd380d11e3fa
Create Date: 2026-06-21 09:32:38.470148

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

revision: str = '54bad840a98c'
down_revision: str | None = 'dd380d11e3fa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_type_assignments', schema=None) as batch_op:
        batch_op.create_foreign_key("delete-orphan-test-type-assignment", 'tests',
                                    ['test_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_type_assignments', schema=None) as batch_op:
        batch_op.drop_constraint("delete-orphan-test-type-assignment", type_='foreignkey')
        batch_op.create_foreign_key("no-delete-orphan-test-type-assignment",
                                    'tests', ['test_id'], ['id'])

    # ### end Alembic commands ###
