# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 Francesco Campanile
"""test_plan_entries.test_plan_id ondelete=cascade for plan deletion

Revision ID: 6ba04a485cec
Revises: fa193170409b
Create Date: 2026-07-14 20:21:59.433628

"""
from collections.abc import Sequence

from alembic import op

revision: str = '6ba04a485cec'
down_revision: str | None = 'fa193170409b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_plan_entries', schema=None) as batch_op:
        batch_op.create_foreign_key(
            "test_plan_entries.test_plan_id ondelete=cascade for plan deletion",
            'test_plans', ['test_plan_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_plan_entries', schema=None) as batch_op:
        batch_op.drop_constraint("test_plan_entries.test_plan_id ondelete=cascade for plan deletion"
                                 , type_='foreignkey')
        batch_op.create_foreign_key(None, 'test_plans', ['test_plan_id'], ['id'])

    # ### end Alembic commands ###
