"""test set name unique

Revision ID: 78f9e1ada61a
Revises: 54bad840a98c
Create Date: 2026-07-02 22:57:35.411015

"""
from collections.abc import Sequence
from typing import Union

from alembic import op

revision: str = '78f9e1ada61a'
down_revision: str | None = '54bad840a98c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_sets', schema=None) as batch_op:
        batch_op.create_unique_constraint("test_set_name_uniqueness", ['name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_sets', schema=None) as batch_op:
        batch_op.drop_constraint("test_set_name_uniqueness", type_='unique')

    # ### end Alembic commands ###
