# ruff: noqa: E501
"""upgrading table with the different types of tests

Revision ID: 89844d4255ff
Revises: f51d59b1b78e
Create Date: 2026-05-27 19:36:01.272322

"""
import uuid
from collections.abc import Sequence
from datetime import datetime

import sqlalchemy as sa

from alembic import op
from assay.models.test import TestTypes, TestTypesCost

revision: str = '89844d4255ff'
down_revision: str | None = 'f51d59b1b78e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('best_for', sa.Text(), nullable=True))
        # create_constraint=True is deliberately omitted here: passing it to
        # add_column() under SQLite batch mode double-emits the CHECK
        # constraint (both from the Enum type's own DDL rendering and from
        # batch mode's table recreation). Instead, add the column bare and
        # create the constraint explicitly, once, right below.
        batch_op.add_column(sa.Column('cost', sa.Enum('very_fast', 'fast', 'expensive',
                                                      name='testtypescost'), nullable=True))
        batch_op.create_check_constraint('testtypescost', "cost IN ('very_fast', 'fast', 'expensive')")
        batch_op.add_column(sa.Column('limitations', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('required_reference', sa.Boolean(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###

    now = datetime.now().astimezone()
    op.bulk_insert(
        sa.table(
            "test_types",
            sa.column("id", sa.Uuid()),
            sa.column("name", sa.Text()),
            sa.column("category", sa.Text()),
            sa.column("description", sa.Text()),
            sa.column("best_for", sa.Text()),
            sa.column("cost", sa.Text()),
            sa.column("limitations", sa.Text()),
            sa.column("required_reference", sa.Boolean()),
            sa.column("is_active", sa.Boolean()),
            sa.column("created_at", sa.DateTime()),
        ),
        [
            {
                "id": uuid.uuid4(),
                "name": "Exact Match",
                "category": TestTypes.deterministic,
                "description": "Checks if the output exactly matches the expected string.",
                "best_for": "Classification tasks, fixed-format outputs, yes/no answers.",
                "cost": TestTypesCost.very_fast,
                "limitations": "Too strict for open-ended outputs; fails on minor formatting differences.",
                "required_reference": True,
                "is_active": True,
                "created_at": now,
            },
            {
                "id": uuid.uuid4(),
                "name": "Regex Match",
                "category": TestTypes.deterministic,
                "description": "Checks if the output matches a regular expression pattern.",
                "best_for": "Validating structured outputs like emails, dates, phone numbers.",
                "cost": TestTypesCost.very_fast,
                "limitations": "Requires writing and maintaining regex patterns; brittle for complex outputs.",
                "required_reference": False,
                "is_active": True,
                "created_at": now,
            },
            {
                "id": uuid.uuid4(),
                "name": "Contains",
                "category": TestTypes.deterministic,
                "description": "Checks if the output contains a specific substring.",
                "best_for": "Verifying presence of required keywords or phrases.",
                "cost": TestTypesCost.very_fast,
                "limitations": "Doesn't validate context; a keyword can appear in a wrong or misleading sentence.",
                "required_reference": False,
                "is_active": True,
                "created_at": now,
            },
            {
                "id": uuid.uuid4(),
                "name": "ROUGE",
                "category": TestTypes.nlp_metric,
                "description": "Measures n-gram overlap between output and expected text.",
                "best_for": "Summarization tasks.",
                "cost": TestTypesCost.fast,
                "limitations": "Doesn't account for semantic meaning; penalizes valid paraphrases.",
                "required_reference": True,
                "is_active": True,
                "created_at": now,
            },
            {
                "id": uuid.uuid4(),
                "name": "BERTScore",
                "category": TestTypes.nlp_metric,
                "description": "Measures semantic similarity using BERT embeddings.",
                "best_for": "Q&A and tasks where paraphrasing is acceptable.",
                "cost": TestTypesCost.fast,
                "limitations": "Requires a BERT model; scores can be hard to interpret without a baseline.",
                "required_reference": True,
                "is_active": True,
                "created_at": now,
            },
            {
                "id": uuid.uuid4(),
                "name": "BLEU",
                "category": TestTypes.nlp_metric,
                "description": "Measures n-gram precision between output and reference text.",
                "best_for": "Machine translation tasks.",
                "cost": TestTypesCost.fast,
                "limitations": "Poorly suited for short texts; doesn't account for recall or semantics.",
                "required_reference": True,
                "is_active": True,
                "created_at": now,
            },
            {
                "id": uuid.uuid4(),
                "name": "METEOR",
                "category": TestTypes.nlp_metric,
                "description": "Measures alignment between output and reference, accounting for synonyms and stemming.",
                "best_for": "Tasks where paraphrasing and word variations are common.",
                "cost": TestTypesCost.fast,
                "limitations": "More complex to compute than BLEU/ROUGE; language support varies.",
                "required_reference": True,
                "is_active": True,
                "created_at": now,
            },
            {
                "id": uuid.uuid4(),
                "name": "Cosine Similarity",
                "category": TestTypes.nlp_metric,
                "description": "Measures semantic similarity between output and reference using vector embeddings.",
                "best_for": "RAG evaluation and semantic search tasks.",
                "cost": TestTypesCost.fast,
                "limitations": "Requires an embedding model; sensitive to the quality of embeddings used.",
                "required_reference": True,
                "is_active": True,
                "created_at": now,
            },
            {
                "id": uuid.uuid4(),
                "name": "LLM as Judge - Correctness",
                "category": TestTypes.llm_as_judge,
                "description": "Uses an LLM to evaluate factual correctness of the output.",
                "best_for": "Open-ended Q&A where exact match is too strict.",
                "cost": TestTypesCost.expensive,
                "limitations": "LLM judgments can be inconsistent; prone to positivity bias.",
                "required_reference": True,
                "is_active": True,
                "created_at": now,
            },
            {
                "id": uuid.uuid4(),
                "name": "LLM as Judge - Relevance",
                "category": TestTypes.llm_as_judge,
                "description": "Uses an LLM to evaluate whether the output is relevant to the input.",
                "best_for": "RAG pipelines and chatbot responses.",
                "cost": TestTypesCost.expensive,
                "limitations": "Subjective; different LLMs may disagree on what counts as relevant.",
                "required_reference": False,
                "is_active": True,
                "created_at": now,
            },
            {
                "id": uuid.uuid4(),
                "name": "LLM as Judge - Bias",
                "category": TestTypes.llm_as_judge,
                "description": "Uses an LLM to detect bias or unfair treatment in the output.",
                "best_for": "Applications serving diverse user groups.",
                "cost": TestTypesCost.expensive,
                "limitations": "The judge LLM may itself carry biases that affect evaluation.",
                "required_reference": False,
                "is_active": True,
                "created_at": now,
            },
            {
                "id": uuid.uuid4(),
                "name": "LLM as Judge - Toxicity",
                "category": TestTypes.llm_as_judge,
                "description": "Uses an LLM to detect harmful or toxic content in the output.",
                "best_for": "Customer-facing applications and public-facing chatbots.",
                "cost": TestTypesCost.expensive,
                "limitations": "May miss subtle toxicity or flag false positives in edge cases.",
                "required_reference": False,
                "is_active": True,
                "created_at": now,
            },
            {
                "id": uuid.uuid4(),
                "name": "LLM as Judge - Hallucination",
                "category": TestTypes.llm_as_judge,
                "description": "Uses an LLM to detect fabricated or unsupported claims in the output.",
                "best_for": "RAG pipelines and factual question answering.",
                "cost": TestTypesCost.expensive,
                "limitations": "The judge LLM may itself hallucinate when verifying facts.",
                "required_reference": True,
                "is_active": True,
                "created_at": now,
            },
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_types', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('required_reference')
        batch_op.drop_column('limitations')
        batch_op.drop_constraint('testtypescost', type_='check')
        batch_op.drop_column('cost')
        batch_op.drop_column('best_for')

    # ### end Alembic commands ###
