# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 Francesco Campanile
"""removal of useless endpoint's tables

Revision ID: 8f93dfb8cdc4
Revises: 0b07ec7d0711
Create Date: 2026-05-18 09:43:58.782670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

revision: str = '8f93dfb8cdc4'
down_revision: Union[str, None] = '0b07ec7d0711'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_case_results_run_id'), table_name='test_case_results')
    op.drop_table('test_case_results')
    op.drop_index(op.f('ix_test_cases_suite_id'), table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_index(op.f('ix_evaluation_runs_suite_id'), table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    op.drop_index(op.f('ix_metric_scores_result_id'), table_name='metric_scores')
    op.drop_table('metric_scores')
    op.drop_table('suites')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suites',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric_scores',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('result_id', sa.CHAR(length=32), nullable=False),
    sa.Column('metric', sa.VARCHAR(length=255), nullable=False),
    sa.Column('value', sa.FLOAT(), nullable=False),
    sa.Column('details', sqlite.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['test_case_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_scores_result_id'), 'metric_scores', ['result_id'], unique=False)
    op.create_table('evaluation_runs',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('suite_id', sa.CHAR(length=32), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['suite_id'], ['suites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_runs_suite_id'), 'evaluation_runs', ['suite_id'], unique=False)
    op.create_table('test_cases',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('suite_id', sa.CHAR(length=32), nullable=False),
    sa.Column('input', sa.TEXT(), nullable=False),
    sa.Column('expected_output', sa.TEXT(), nullable=True),
    sa.Column('context', sqlite.JSON(), nullable=True),
    sa.Column('metadata', sqlite.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['suite_id'], ['suites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_cases_suite_id'), 'test_cases', ['suite_id'], unique=False)
    op.create_table('test_case_results',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('run_id', sa.CHAR(length=32), nullable=True),
    sa.Column('case_id', sa.CHAR(length=32), nullable=False),
    sa.Column('actual_output', sa.TEXT(), nullable=False),
    sa.Column('latency_ms', sa.FLOAT(), nullable=True),
    sa.Column('error', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_case_results_run_id'), 'test_case_results', ['run_id'], unique=False)
    # ### end Alembic commands ###
