"""adding tables to save tests and executions

Revision ID: a53e4a6cf00b
Revises: 8f93dfb8cdc4
Create Date: 2026-05-18 11:42:06.128870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a53e4a6cf00b'
down_revision: Union[str, None] = '8f93dfb8cdc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_tests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('input', sa.Text(), nullable=False),
    sa.Column('expected_output', sa.Text(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='teststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('executed_tests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pending_test_id', sa.Uuid(), nullable=False),
    sa.Column('actual_output', sa.Text(), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pending_test_id'], ['pending_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executed_tests_pending_test_id'), 'executed_tests', ['pending_test_id'], unique=False)
    op.create_table('statistical_verifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('executed_test_id', sa.Uuid(), nullable=False),
    sa.Column('metric', sa.String(length=255), nullable=False),
    sa.Column('test_type', sa.String(length=50), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('alpha', sa.Float(), nullable=False),
    sa.Column('alternative', sa.String(length=20), nullable=False),
    sa.Column('z_statistic', sa.Float(), nullable=False),
    sa.Column('p_value', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('result_detail', sa.JSON(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['executed_test_id'], ['executed_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statistical_verifications_executed_test_id'), 'statistical_verifications', ['executed_test_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statistical_verifications_executed_test_id'), table_name='statistical_verifications')
    op.drop_table('statistical_verifications')
    op.drop_index(op.f('ix_executed_tests_pending_test_id'), table_name='executed_tests')
    op.drop_table('executed_tests')
    op.drop_table('pending_tests')
    # ### end Alembic commands ###
