"""add test type config fields and per-assignment config

Revision ID: c7891554368a
Revises: e8581c809e17
Create Date: 2026-09-23 22:55:26.081722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

revision: str = 'c7891554368a'
down_revision: Union[str, None] = 'e8581c809e17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # test_set_entries already has 9 rows in the dev DB — server_default='[]'
    # is required so the NOT NULL add succeeds against them. Per
    # docs/test_type_config/dev_notes.md note 4 / next_move.md Phase 1.4,
    # existing rows' old test_type_names data is deliberately not carried
    # over into the new shape (pre-production, no deployed consumers).
    with op.batch_alter_table('test_set_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_type_assignments', sa.JSON(),
                                      nullable=False, server_default=sa.text("'[]'")))
        batch_op.drop_column('test_type_names')

    with op.batch_alter_table('test_type_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config', sa.JSON(), nullable=True))

    # test_types already has 13 seeded rows — same server_default reasoning,
    # immediately overwritten below with each type's real config_fields.
    with op.batch_alter_table('test_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config_fields', sa.JSON(),
                                      nullable=False, server_default=sa.text("'[]'")))
        batch_op.drop_column('required_reference')

    _seed_config_fields()


def _seed_config_fields() -> None:
    """Populate config_fields for every seeded test type.

    Values exactly as tabulated in docs/test_type_config/dev_notes.md note
    2/7 — kind "reference" resolves to expected_output rather than being
    stored per-assignment; "rubric" fields are optional on every
    llm_as_judge type.
    """
    test_types_table = sa.table(
        "test_types",
        sa.column("name", sa.Text()),
        sa.column("config_fields", sa.JSON()),
    )

    reference_field = [
        {"key": "reference", "label": "Reference text", "kind": "reference", "required": True}
    ]

    config_fields_by_name = {
        "Exact Match": [
            {"key": "reference", "label": "Expected output", "kind": "reference", "required": True},
        ],
        "Regex Match": [
            {"key": "pattern", "label": "Regex pattern", "kind": "multiline", "required": True},
        ],
        "Contains": [
            {"key": "substring", "label": "Required substring",
             "kind": "multiline", "required": True},
        ],
        "ROUGE": reference_field,
        "BERTScore": reference_field,
        "BLEU": reference_field,
        "METEOR": reference_field,
        "Cosine Similarity": reference_field,
        "Correctness": [
            *reference_field,
            {"key": "rubric", "label": "Custom correctness rubric (optional)",
             "kind": "rubric", "required": False},
        ],
        "Relevance": [
            {"key": "rubric", "label": "Custom relevance rubric (optional)",
             "kind": "rubric", "required": False},
        ],
        "Bias": [
            {"key": "rubric", "label": "Custom bias rubric (optional)",
             "kind": "rubric", "required": False},
        ],
        "Toxicity": [
            {"key": "rubric", "label": "Custom toxicity rubric (optional)",
             "kind": "rubric", "required": False},
        ],
        "Hallucination": [
            *reference_field,
            {"key": "rubric", "label": "Custom hallucination rubric (optional)",
             "kind": "rubric", "required": False},
        ],
    }

    for name, config_fields in config_fields_by_name.items():
        op.execute(
            test_types_table.update()
            .where(test_types_table.c.name == name)
            .values(config_fields=config_fields)
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_reference', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('config_fields')

    with op.batch_alter_table('test_type_assignments', schema=None) as batch_op:
        batch_op.drop_column('config')

    with op.batch_alter_table('test_set_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_type_names', sqlite.JSON(),
                                      nullable=False, server_default=sa.text("'[]'")))
        batch_op.drop_column('test_type_assignments')

    # ### end Alembic commands ###
