# ruff: noqa: E501
"""add test management tables

Revision ID: dd380d11e3fa
Revises: 20cf133882df
Create Date: 2026-05-28 15:20:14.083044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

revision: str = 'dd380d11e3fa'
down_revision: Union[str, None] = '20cf133882df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_type_assignments',
    sa.Column('test_id', sa.Uuid(), nullable=False),
    sa.Column('test_type_name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.ForeignKeyConstraint(['test_type_name'], ['test_types.name'], ),
    sa.PrimaryKeyConstraint('test_id', 'test_type_name')
    )
    with op.batch_alter_table('statistical_verifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('executed_test_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_statistical_verifications_executed_test_id'), ['executed_test_id'], unique=False)
        batch_op.create_foreign_key('fk_statistical_verifications_executed_test_id', 'test_runs', ['executed_test_id'], ['id'])
        batch_op.drop_constraint('fk_statistical_verifications_test_run_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_statistical_verifications_test_run_id'))
        batch_op.drop_column('test_run_id')

    with op.batch_alter_table('test_set_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_type_names', sa.JSON(), nullable=False))
        batch_op.drop_column('test_type_ids')

    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.alter_column('expected_output',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('model_output',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('test_type_ids')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_type_ids', sqlite.JSON(), nullable=False))
        batch_op.alter_column('model_output',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('expected_output',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('test_set_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_type_ids', sqlite.JSON(), nullable=False))
        batch_op.drop_column('test_type_names')

    with op.batch_alter_table('statistical_verifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_run_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_statistical_verifications_test_run_id'), ['test_run_id'], unique=False)
        batch_op.create_foreign_key('fk_statistical_verifications_test_run_id', 'test_runs', ['test_run_id'], ['id'])
        batch_op.drop_constraint('fk_statistical_verifications_executed_test_id', type_='foreignkey')
        batch_op.drop_column('executed_test_id')

    op.drop_table('test_type_assignments')
    # ### end Alembic commands ###
