"""test_set_id nullable=True

Revision ID: e7dd644e8fc5
Revises: b039ee8d1fef
Create Date: 2026-07-14 14:12:21.204222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e7dd644e8fc5'
down_revision: Union[str, None] = 'b039ee8d1fef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_set_entries', schema=None) as batch_op:
        batch_op.alter_column('test_set_id',
               existing_type=sa.CHAR(length=32),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_set_entries', schema=None) as batch_op:
        batch_op.alter_column('test_set_id',
               existing_type=sa.CHAR(length=32),
               nullable=False)

    # ### end Alembic commands ###
