# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 Francesco Campanile
"""removal test_runs.test_plan_id and test_runs.test_plan

Revision ID: e8581c809e17
Revises: 6ba04a485cec
Create Date: 2026-07-16 01:27:11.347634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e8581c809e17'
down_revision: Union[str, None] = '6ba04a485cec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_runs_test_plan_id'))
        batch_op.drop_constraint(batch_op.f('fk_test_runs_test_plan_id'), type_='foreignkey')
        batch_op.drop_column('test_plan_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_plan_id', sa.CHAR(length=32), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_test_runs_test_plan_id'), 'test_plans', ['test_plan_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_test_runs_test_plan_id'), ['test_plan_id'], unique=False)

    # ### end Alembic commands ###
