# ruff: noqa: E501
"""adding table with the different type of tests

Revision ID: f51d59b1b78e
Revises: 4945001a5a26
Create Date: 2026-05-27 18:55:01.804895

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'f51d59b1b78e'
down_revision: str | None = '4945001a5a26'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('deterministic', 'nlp_metric', 'llm_as_judge',
                                  name='testtypes', create_constraint=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('dataset_rows') as batch_op:
        batch_op.alter_column('expected_output', existing_type=sa.TEXT(), nullable=False)
        batch_op.alter_column('model_output', existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset_rows') as batch_op:
        batch_op.alter_column('model_output', existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column('expected_output', existing_type=sa.TEXT(), nullable=True)
    op.drop_table('test_types')
    # ### end Alembic commands ###
