"""The estimate's Swagger example with a history: the FE canvas's state (a),
a set entry whose four checks ran 40 times — Relevance passed 38, Correctness
39, the other two every time. Taken from a real response
(tests/statistics/test_odds.py checks it still is one, the curve cut to
every fourth point), so it can't drift from what the API returns."""

# every fourth point of the curve, and the best; the response has all 85
ODDS_EVERY = 4

WITH_HISTORY = {'scope': {'kind': 'test_set',
           'id': '4e86003a-9e28-4c93-a08e-f99c6acbaab6',
           'name': 'Support answers'},
 'statistical_test': 'binomial_gate',
 'engine': 'binomial_gate',
 'parameters': {'target': 0.9, 'confidence': 0.95},
 'floor': 29,
 'floor_explanation': 'A few in a row can be luck. A check that really passed only 9 times in '
                      '10 would pass 29 times in a row less than 1 time in 20, so 29 out of 29 '
                      'is enough to be 95% sure. With fewer, even a perfect record could be '
                      'luck.',
 'suggestions': [{'times': 29,
                  'kind': 'floor',
                  'label': '29 times · the least that can answer',
                  'default': False,
                  'chance': 0.026,
                  'failures_allowed': 0,
                  'outcome': {'passed': 0.0227, 'inconclusive': 0.9452, 'failed': 0.0321},
                  'likely_undecided': {'entry_id': 'd4e5f6a7-b8c9-0123-def4-56789012345a',
                                       'label': 'Relevance'}},
                 {'times': 715,
                  'kind': 'worth_its_cost',
                  'label': '715 times · 66% chance, worth its cost',
                  'default': True,
                  'chance': 0.6624,
                  'failures_allowed': 58,
                  'outcome': {'passed': 0.5284, 'inconclusive': 0.3056, 'failed': 0.1661},
                  'likely_undecided': {'entry_id': 'd4e5f6a7-b8c9-0123-def4-56789012345a',
                                       'label': 'Relevance'}},
                 {'times': 977,
                  'kind': 'best_chance',
                  'label': '977 times · 71% chance, the best',
                  'default': False,
                  'chance': 0.7114,
                  'failures_allowed': 82,
                  'outcome': {'passed': 0.5589, 'inconclusive': 0.2589, 'failed': 0.1821},
                  'likely_undecided': {'entry_id': 'd4e5f6a7-b8c9-0123-def4-56789012345a',
                                       'label': 'Relevance'}}],
 'times': 715,
 'rule': {'times': 715, 'pass_at_least': 657, 'fail_at_most': 629},
 'runs_per_time': 1,
 'runs_total': 715,
 'calls': {'application': {'per_time': 1, 'total': 715},
           'judge': {'per_time': 2, 'total': 1430}},
 'checks_total': 4,
 'checks_applicable': 4,
 'entries': [{'entry_id': 'd4e5f6a7-b8c9-0123-def4-56789012345a',
              'test_id': 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
              'test_set_id': '4e86003a-9e28-4c93-a08e-f99c6acbaab6',
              'test_set_name': 'Support answers',
              'name': 'Reset a password',
              'recorded_answer': False,
              'checks': [{'label': 'Contains',
                          'test_type': 'Contains',
                          'applies': True,
                          'reason': None,
                          'target': 0.9,
                          'left_out': False,
                          'history': {'runs': 40,
                                      'passed': 40,
                                      'rate': 1.0,
                                      'mean': None,
                                      'sd': None},
                          'outlook': 'likely_pass',
                          'outlook_reason': 'Passed 40 of its last 40 runs: likely to pass at '
                                            'least 9 times in 10.',
                          'certain_result': None,
                          'size_needed': 142,
                          'best_chance': 0.9786,
                          'cheaper': []},
                         {'label': 'Correctness',
                          'test_type': 'Correctness',
                          'applies': True,
                          'reason': None,
                          'target': 0.9,
                          'left_out': False,
                          'history': {'runs': 40,
                                      'passed': 39,
                                      'rate': 0.975,
                                      'mean': None,
                                      'sd': None},
                          'outlook': 'likely_pass',
                          'outlook_reason': 'Passed 39 of its last 40 runs: likely to pass at '
                                            'least 9 times in 10.',
                          'certain_result': None,
                          'size_needed': 814,
                          'best_chance': 0.9108,
                          'cheaper': []},
                         {'label': 'Mentions',
                          'test_type': 'Contains',
                          'applies': True,
                          'reason': None,
                          'target': 0.9,
                          'left_out': False,
                          'history': {'runs': 40,
                                      'passed': 40,
                                      'rate': 1.0,
                                      'mean': None,
                                      'sd': None},
                          'outlook': 'likely_pass',
                          'outlook_reason': 'Passed 40 of its last 40 runs: likely to pass at '
                                            'least 9 times in 10.',
                          'certain_result': None,
                          'size_needed': 142,
                          'best_chance': 0.9786,
                          'cheaper': []},
                         {'label': 'Relevance',
                          'test_type': 'Relevance',
                          'applies': True,
                          'reason': None,
                          'target': 0.9,
                          'left_out': False,
                          'history': {'runs': 40,
                                      'passed': 38,
                                      'rate': 0.95,
                                      'mean': None,
                                      'sd': None},
                          'outlook': 'too_close',
                          'outlook_reason': 'Passed 38 of its last 40 runs: too close to 9 '
                                            'times in 10 to tell cheaply.',
                          'certain_result': None,
                          'size_needed': None,
                          'best_chance': 0.8158,
                          'cheaper': [{'kind': 'lower_target',
                                       'label': 'Relevance at "at least 17 times in 20": at '
                                                'most 82%, 627 times for 77%',
                                       'check': {'entry_id': 'd4e5f6a7-b8c9-0123-def4-56789012345a',
                                                 'label': 'Relevance'},
                                       'checks': [],
                                       'target': 0.85,
                                       'confidence': None,
                                       'times': 627,
                                       'chance': 0.7696,
                                       'reaches_goal': False,
                                       'best_chance': 0.8191,
                                       'best_times': 1000,
                                       'judge_calls_saved_per_time': 0},
                                      {'kind': 'lower_target',
                                       'label': 'Relevance at "at least 8 times in 10": at '
                                                'most 86%, 582 times for 81%',
                                       'check': {'entry_id': 'd4e5f6a7-b8c9-0123-def4-56789012345a',
                                                 'label': 'Relevance'},
                                       'checks': [],
                                       'target': 0.8,
                                       'confidence': None,
                                       'times': 582,
                                       'chance': 0.8132,
                                       'reaches_goal': False,
                                       'best_chance': 0.8604,
                                       'best_times': 999,
                                       'judge_calls_saved_per_time': 0},
                                      {'kind': 'lower_target',
                                       'label': 'Relevance at "at least 15 times in 20": at '
                                                'most 87%, 560 times for 82%',
                                       'check': {'entry_id': 'd4e5f6a7-b8c9-0123-def4-56789012345a',
                                                 'label': 'Relevance'},
                                       'checks': [],
                                       'target': 0.75,
                                       'confidence': None,
                                       'times': 560,
                                       'chance': 0.8206,
                                       'reaches_goal': False,
                                       'best_chance': 0.8702,
                                       'best_times': 999,
                                       'judge_calls_saved_per_time': 0},
                                      {'kind': 'leave_out',
                                       'label': 'Leave Relevance out: at most 87%, 560 times '
                                                'for 82%',
                                       'check': {'entry_id': 'd4e5f6a7-b8c9-0123-def4-56789012345a',
                                                 'label': 'Relevance'},
                                       'checks': [],
                                       'target': None,
                                       'confidence': None,
                                       'times': 560,
                                       'chance': 0.8235,
                                       'reaches_goal': False,
                                       'best_chance': 0.8721,
                                       'best_times': 999,
                                       'judge_calls_saved_per_time': 1}]}]}],
 'warnings': [],
 'goal': 0.9,
 'goal_reachable': False,
 'best_chance': 0.7114,
 'best_times': 977,
 'odds_summary': 'Even 977 times give every check an answer only 71% of the time; 715 times '
                 'give 66% for 27% fewer runs.',
 'driving_check': {'entry_id': 'd4e5f6a7-b8c9-0123-def4-56789012345a', 'label': 'Relevance'},
 'odds': [{'times': 29, 'chance': 0.026},
          {'times': 89, 'chance': 0.202},
          {'times': 142, 'chance': 0.3174},
          {'times': 191, 'chance': 0.3939},
          {'times': 239, 'chance': 0.4447},
          {'times': 286, 'chance': 0.491},
          {'times': 333, 'chance': 0.5167},
          {'times': 379, 'chance': 0.5458},
          {'times': 425, 'chance': 0.5692},
          {'times': 470, 'chance': 0.5896},
          {'times': 515, 'chance': 0.6066},
          {'times': 560, 'chance': 0.621},
          {'times': 604, 'chance': 0.6342},
          {'times': 649, 'chance': 0.6448},
          {'times': 693, 'chance': 0.6548},
          {'times': 737, 'chance': 0.6698},
          {'times': 781, 'chance': 0.6773},
          {'times': 825, 'chance': 0.6841},
          {'times': 869, 'chance': 0.6901},
          {'times': 912, 'chance': 0.7015},
          {'times': 956, 'chance': 0.7062},
          {'times': 977, 'chance': 0.7114},
          {'times': 999, 'chance': 0.7109}],
 'cheaper': [{'kind': 'leave_out',
              'label': 'Leave Relevance and Correctness out: 90% at 286 times',
              'check': None,
              'checks': [{'entry_id': 'd4e5f6a7-b8c9-0123-def4-56789012345a',
                          'label': 'Relevance'},
                         {'entry_id': 'd4e5f6a7-b8c9-0123-def4-56789012345a',
                          'label': 'Correctness'}],
              'target': None,
              'confidence': None,
              'times': 286,
              'chance': 0.9023,
              'reaches_goal': True,
              'best_chance': 0.9576,
              'best_times': 999,
              'judge_calls_saved_per_time': 2},
             {'kind': 'less_sure',
              'label': '90% sure: at most 77%, 653 times for 72%',
              'check': None,
              'checks': [],
              'target': None,
              'confidence': 0.9,
              'times': 653,
              'chance': 0.7205,
              'reaches_goal': False,
              'best_chance': 0.7698,
              'best_times': 964,
              'judge_calls_saved_per_time': 0}],
 'trial': None}
